name: Second Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
    - name: print hello world
      run: echo "Hello World"

  

     
