name: Multiple Branches for Pull Request Workflow

on:
  pull_request:
    branches:
      - main
      - feature1
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: linux
      run: |
        echo "This job is running on an Ubuntu runner"
        echo "Runner OS is $RUNNER_OS"
        


 

  

     
