name: Multiple Branches for Pull Request Workflow

on:
  push:
    paths:
      - File
      
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: linux
      run: |
        echo "This job is running on an Ubuntu runner"
        echo "Runner OS is $RUNNER_OS"
        


 

  

     
