name: Second Workflow

on:
  schedule: 

    - cron: 
        '2 * * * *' 

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
    - name: print hello world
      run: echo "Hello World"

  

     
