name: Deployment for env 

on:
  push:
    branches:
      - main
      - dev
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      STAGING_API_URL: https://staging-api.example.com 
      PRODUCTION_API_URL: https://api.example.com 
      VERSION: v1.1.0
      
    steps:
    - name: Set Env
      run: |
        if [ ${{ github.ref }} == "main" ]; then
          echo "Using PRODUCTION_API_URL: $PRODUCTION_API_URL"
          echo "Deploying to Production with version $VERSION"
        else 
          echo "Using STAGING_API_URL: $STAGING_API_URL"
          echo "Deploying to Staging with version $VERSION"
        


 

  

     
